language: python
python:
    - "2.7"
    - "pypy"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"

matrix:
  include:
    - python: "3.6"
      script: tox -e linters
      name: linters

install: pip install tox pytest
script: sh scripts/runtox.sh
