language: python
python:
    - "2.7"
    - "pypy"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"

matrix:
  include:
    - python: "3.7"
      script: tox -e linters

install: pip install tox pytest
script: sh scripts/runtox.sh
